export type EnterpriseFeatureStatus = "backlog" | "planned" | "in_progress" | "live"

export type EnterpriseFeatureCategory =
  | "AI Intelligence"
  | "Conversion Engine"
  | "Workflow Automation"
  | "Collaboration & Governance"
  | "Security & Compliance"
  | "Ecosystem & Mobility"

export interface EnterpriseFeatureDefinition {
  id: string
  title: string
  category: EnterpriseFeatureCategory
  summary: string
  impact: string
  defaultHref: string
  kpis: string[]
  sprintTemplate: string[]
}

export interface EnterpriseFeatureRollout {
  featureId: string
  status: EnterpriseFeatureStatus
  priority: number
  owner: string
  notes: string
  lastRunAt: string | null
  updatedAt: string | null
}

export interface EnterpriseFeatureWithRollout extends EnterpriseFeatureDefinition, EnterpriseFeatureRollout {}

const FEATURE_CATALOG: EnterpriseFeatureDefinition[] = [
  {
    id: "ai-role-match-engine",
    title: "AI Role Match Engine",
    category: "AI Intelligence",
    summary: "Scores every role against skills, narrative strength, and recent conversion history.",
    impact: "Prioritizes the highest expected-conversion opportunities.",
    defaultHref: "/app/roles",
    kpis: ["Top-10 role fit score", "Qualified role coverage"],
    sprintTemplate: [
      "Ingest 25 new role postings and run match scoring.",
      "Promote top-fit roles into application sprint queue.",
      "Review low-fit roles and capture explicit gap reasons.",
      "Rebalance weekly target based on fit-quality trend.",
    ],
  },
  {
    id: "jd-resume-tailor",
    title: "One-Click JD Resume Tailor",
    category: "AI Intelligence",
    summary: "Generates job-description aligned resume variants with section-level diffs.",
    impact: "Increases response probability for each targeted role.",
    defaultHref: "/app/resumes",
    kpis: ["Tailored resume count", "ATS delta vs baseline"],
    sprintTemplate: [
      "Select 10 top-priority roles for tailoring.",
      "Generate role-specific summary and impact bullets.",
      "Run ATS scan and resolve low-confidence sections.",
      "Ship final tailored packs to application queue.",
    ],
  },
  {
    id: "resume-ab-testing",
    title: "Resume A/B Testing",
    category: "Conversion Engine",
    summary: "Tracks variant-level callback performance and identifies winning structures.",
    impact: "Turns resume optimization into measurable conversion improvement.",
    defaultHref: "/app/insights",
    kpis: ["Variant callback rate", "Winning variant confidence"],
    sprintTemplate: [
      "Define two variant hypotheses for target role families.",
      "Distribute variants across equivalent opportunity sets.",
      "Track response and interview movement by variant.",
      "Promote winner and archive weaker pattern.",
    ],
  },
  {
    id: "cover-letter-outreach-sequences",
    title: "Cover Letter + Outreach Sequence Generator",
    category: "AI Intelligence",
    summary: "Builds application-specific cover letters and multi-step follow-up scripts.",
    impact: "Improves recruiter response and keeps outreach consistent.",
    defaultHref: "/app/cover-letters",
    kpis: ["Outreach sequence completion", "Reply rate"],
    sprintTemplate: [
      "Generate sequence templates for top 12 companies.",
      "Schedule day-0, day-3, day-7 outreach touches.",
      "Personalize hooks from company intelligence snapshots.",
      "Track reply outcomes and refresh weak templates.",
    ],
  },
  {
    id: "voice-interview-simulator",
    title: "Voice Interview Simulator",
    category: "AI Intelligence",
    summary: "Runs timed mock interviews with scoring on structure, clarity, and confidence.",
    impact: "Raises interview consistency before high-stakes rounds.",
    defaultHref: "/app/interviews",
    kpis: ["Mock score trend", "Confidence index"],
    sprintTemplate: [
      "Run three role-specific voice mock sessions.",
      "Capture weak-answer themes and rewrite patterns.",
      "Practice improved responses under 90-second limit.",
      "Log score lift and lock weekly drill cadence.",
    ],
  },
  {
    id: "star-story-bank",
    title: "STAR Story Bank",
    category: "Conversion Engine",
    summary: "Maintains reusable STAR narratives mapped to competencies and role families.",
    impact: "Speeds interview prep and improves answer quality.",
    defaultHref: "/app/interviews",
    kpis: ["Story coverage by competency", "Reuse rate in interviews"],
    sprintTemplate: [
      "Add or refine five high-impact STAR stories.",
      "Tag each story by competency and role archetype.",
      "Attach quantifiable outcomes to every story.",
      "Run retrieval drills with random competency prompts.",
    ],
  },
  {
    id: "coding-interview-lane",
    title: "Coding Interview Prep Lane",
    category: "Conversion Engine",
    summary: "Curates timed coding drills with weak-topic recurrence and trend analytics.",
    impact: "Improves technical interview pass-through rates.",
    defaultHref: "/app/interviews",
    kpis: ["Solved set completion", "Time-to-solution trend"],
    sprintTemplate: [
      "Set weekly drill target by difficulty mix.",
      "Run timed sessions and log misses by pattern.",
      "Generate remediation sequence for weak topics.",
      "Re-test weak topics after 72-hour spacing.",
    ],
  },
  {
    id: "offer-probability-forecasting",
    title: "Offer Probability Forecasting",
    category: "Conversion Engine",
    summary: "Estimates offer likelihood by stage velocity, quality signals, and historical conversion.",
    impact: "Improves planning clarity and decision timing.",
    defaultHref: "/app/forecast",
    kpis: ["Projected offers (8-12w)", "Forecast error rate"],
    sprintTemplate: [
      "Refresh baseline conversion assumptions from last 30 days.",
      "Run conservative, baseline, and aggressive scenarios.",
      "Identify top levers with highest offer sensitivity.",
      "Translate chosen scenario into weekly action quotas.",
    ],
  },
  {
    id: "salary-negotiation-copilot",
    title: "Salary Negotiation Copilot",
    category: "Conversion Engine",
    summary: "Builds market-grounded negotiation scripts and compensation decision frameworks.",
    impact: "Increases expected package quality with less negotiation risk.",
    defaultHref: "/app/salary-insights",
    kpis: ["Comp benchmark coverage", "Negotiation readiness score"],
    sprintTemplate: [
      "Collect compensation data for top target companies.",
      "Generate three negotiation script variants.",
      "Define walk-away and stretch thresholds.",
      "Run rehearsal and finalize decision matrix.",
    ],
  },
  {
    id: "skill-gap-analyzer",
    title: "Skill Gap Analyzer",
    category: "AI Intelligence",
    summary: "Detects role-fit skill gaps and produces compact upskilling plans.",
    impact: "Focuses effort on the highest ROI skill improvements.",
    defaultHref: "/app/goals",
    kpis: ["Gap closure velocity", "Readiness score uplift"],
    sprintTemplate: [
      "Select target roles and extract required competencies.",
      "Score current proficiency and identify top three gaps.",
      "Assign daily micro-learning blocks for each gap.",
      "Review progress and refresh gap priorities weekly.",
    ],
  },
  {
    id: "application-autopilot",
    title: "Application Autopilot",
    category: "Workflow Automation",
    summary: "Automatically schedules next actions, reminders, and escalation paths.",
    impact: "Prevents pipeline drift and missed follow-up windows.",
    defaultHref: "/app/command-center",
    kpis: ["Autopilot coverage", "On-time follow-up rate"],
    sprintTemplate: [
      "Enable autopilot for all active applications.",
      "Configure SLA tiers by application stage.",
      "Set escalation rules for stale records.",
      "Audit autopilot misses and patch rule gaps.",
    ],
  },
  {
    id: "pipeline-sla-tracker",
    title: "Pipeline SLA Tracker",
    category: "Workflow Automation",
    summary: "Surfaces stale, overdue, and no-action records with severity-level queues.",
    impact: "Improves operational discipline and conversion reliability.",
    defaultHref: "/app/control-tower",
    kpis: ["SLA compliance", "Stale record count"],
    sprintTemplate: [
      "Review red-zone SLA queue every morning.",
      "Resolve overdue records with explicit next actions.",
      "Set owner-level accountability by stage.",
      "Publish weekly SLA compliance trend.",
    ],
  },
  {
    id: "unified-communication-inbox",
    title: "Unified Communication Inbox",
    category: "Workflow Automation",
    summary: "Consolidates recruiting communications and links every touchpoint to pipeline entities.",
    impact: "Reduces context switching and missed communication actions.",
    defaultHref: "/app/applications",
    kpis: ["Message-to-record linkage", "Missed reply incidents"],
    sprintTemplate: [
      "Normalize inbound communication into a single queue.",
      "Attach each thread to role and application entities.",
      "Set response SLA for inbound messages.",
      "Escalate unanswered messages past SLA threshold.",
    ],
  },
  {
    id: "relationship-crm",
    title: "Relationship CRM",
    category: "Collaboration & Governance",
    summary: "Tracks recruiters, referrals, and hiring managers with engagement history.",
    impact: "Improves relationship-based opportunity conversion.",
    defaultHref: "/app/workspaces",
    kpis: ["Active relationship count", "Warm-contact conversion"],
    sprintTemplate: [
      "Import and deduplicate current contact graph.",
      "Score contacts by influence and recency.",
      "Build personalized re-engagement sequences.",
      "Track introductions and follow-through outcomes.",
    ],
  },
  {
    id: "referral-graph",
    title: "Referral Graph + Warm Intro Finder",
    category: "Collaboration & Governance",
    summary: "Maps referral paths and recommends highest-probability intro routes.",
    impact: "Raises referral acquisition efficiency.",
    defaultHref: "/app/workspaces",
    kpis: ["Referral path coverage", "Warm intro success rate"],
    sprintTemplate: [
      "Map second-degree network paths for target companies.",
      "Rank referral paths by closeness and relevance.",
      "Generate personalized warm-intro requests.",
      "Measure conversion from request to referral.",
    ],
  },
  {
    id: "company-intelligence-briefs",
    title: "Company Intelligence Briefs",
    category: "AI Intelligence",
    summary: "Creates pre-application intelligence packets with risk/opportunity signals.",
    impact: "Improves narrative relevance and interview preparation.",
    defaultHref: "/app/horizons",
    kpis: ["Briefs generated", "Brief usage in applications"],
    sprintTemplate: [
      "Generate briefs for this week's top target companies.",
      "Extract strategy, product, and team risk signals.",
      "Embed briefing insights into outreach messaging.",
      "Review impact on response and interview quality.",
    ],
  },
  {
    id: "hiring-manager-persona",
    title: "Hiring Manager Persona Insights",
    category: "AI Intelligence",
    summary: "Synthesizes likely hiring manager priorities and communication preferences.",
    impact: "Improves pitch alignment in outreach and interviews.",
    defaultHref: "/app/ai-studio",
    kpis: ["Persona coverage", "Message resonance score"],
    sprintTemplate: [
      "Generate persona hypotheses for top opportunities.",
      "Tailor value proposition per persona profile.",
      "Draft personalized outreach and answer framing.",
      "Record engagement lift by persona strategy.",
    ],
  },
  {
    id: "github-portfolio-analyzer",
    title: "GitHub + Portfolio Analyzer",
    category: "Conversion Engine",
    summary: "Audits project portfolio quality, relevance, and storytelling gaps.",
    impact: "Strengthens technical credibility for high-signal roles.",
    defaultHref: "/app/documents",
    kpis: ["Portfolio quality score", "Project relevance index"],
    sprintTemplate: [
      "Assess top repositories for impact readability.",
      "Prioritize repo improvements for target role fit.",
      "Add concise project narratives and outcomes.",
      "Update resume links with refreshed projects.",
    ],
  },
  {
    id: "linkedin-optimizer",
    title: "LinkedIn Optimizer",
    category: "Conversion Engine",
    summary: "Optimizes headline, summary, and evidence blocks for recruiter discovery.",
    impact: "Increases inbound recruiter visibility.",
    defaultHref: "/app/help",
    kpis: ["Profile strength score", "Inbound recruiter activity"],
    sprintTemplate: [
      "Rewrite headline and summary for target role clusters.",
      "Refresh experience bullets with quantified impact.",
      "Align skills and endorsements with role strategy.",
      "Review inbound trend and refine messaging.",
    ],
  },
  {
    id: "ats-compliance-scanner",
    title: "ATS Compliance Scanner",
    category: "AI Intelligence",
    summary: "Validates resume structure, keyword coverage, and formatting safety.",
    impact: "Reduces ATS rejection risk at submission stage.",
    defaultHref: "/app/resumes",
    kpis: ["ATS pass rate", "Critical issue count"],
    sprintTemplate: [
      "Run ATS scan on all active resume variants.",
      "Resolve keyword and format-level blockers.",
      "Re-test and compare score uplift vs baseline.",
      "Lock ATS-safe templates for weekly usage.",
    ],
  },
  {
    id: "no-code-workflow-builder",
    title: "No-Code Workflow Builder",
    category: "Workflow Automation",
    summary: "Creates if-this-then-that job-search workflows without code.",
    impact: "Scales repeatable execution with fewer manual steps.",
    defaultHref: "/app/command-center",
    kpis: ["Workflow automations active", "Manual hours saved"],
    sprintTemplate: [
      "Define top repetitive process candidates.",
      "Build trigger-action workflows for each process.",
      "Run dry tests and verify exception handling.",
      "Promote stable workflows to production.",
    ],
  },
  {
    id: "shared-workspaces",
    title: "Shared Workspaces",
    category: "Collaboration & Governance",
    summary: "Supports mentor and team collaboration across modules and decisions.",
    impact: "Improves visibility, speed, and accountability.",
    defaultHref: "/app/workspaces",
    kpis: ["Active collaborators", "Shared decision cycle time"],
    sprintTemplate: [
      "Create workspace pods by operating focus.",
      "Invite members with role-based permissions.",
      "Attach comments and decisions to key entities.",
      "Run weekly workspace review cadence.",
    ],
  },
  {
    id: "approval-workflows",
    title: "Approval Workflows",
    category: "Collaboration & Governance",
    summary: "Adds signoff paths for resumes, outreach, and strategic changes.",
    impact: "Improves quality control before external execution.",
    defaultHref: "/app/program-office",
    kpis: ["Approval turnaround time", "Pre-send defect rate"],
    sprintTemplate: [
      "Define approval policies for high-risk assets.",
      "Route submissions to appropriate approvers.",
      "Track bottlenecks in approval queue.",
      "Reduce turnaround with SLA-backed review windows.",
    ],
  },
  {
    id: "enterprise-auth",
    title: "Enterprise Auth (SSO + SCIM + RBAC)",
    category: "Security & Compliance",
    summary: "Supports scalable identity and access controls for organization deployments.",
    impact: "Improves security posture and enterprise readiness.",
    defaultHref: "/app/security-center",
    kpis: ["Provisioning success rate", "Access policy coverage"],
    sprintTemplate: [
      "Audit current role and permission assignments.",
      "Define SSO-ready role mapping matrix.",
      "Set SCIM lifecycle policy requirements.",
      "Run access review and revoke stale sessions.",
    ],
  },
  {
    id: "security-compliance-center",
    title: "Security + Compliance Center",
    category: "Security & Compliance",
    summary: "Centralizes audit logs, retention controls, exports, and deletion workflows.",
    impact: "Meets governance and compliance needs for enterprise usage.",
    defaultHref: "/app/security-center",
    kpis: ["Audit completeness", "Request SLA compliance"],
    sprintTemplate: [
      "Review weekly anomaly and audit event summaries.",
      "Verify retention and export request handling.",
      "Close unresolved security findings.",
      "Publish compliance evidence snapshot.",
    ],
  },
  {
    id: "scenario-planning-dashboard",
    title: "Scenario Planning Dashboard",
    category: "Conversion Engine",
    summary: "Evaluates plan scenarios and recommends the best weekly execution mix.",
    impact: "Improves decision quality under uncertainty.",
    defaultHref: "/app/forecast",
    kpis: ["Scenario adoption rate", "KPI variance reduction"],
    sprintTemplate: [
      "Model conservative, baseline, and aggressive plans.",
      "Stress-test assumptions against current funnel data.",
      "Choose scenario with best risk-adjusted outcome.",
      "Translate scenario into actionable weekly targets.",
    ],
  },
  {
    id: "weekly-executive-report",
    title: "Weekly Executive Report Generator",
    category: "Collaboration & Governance",
    summary: "Automatically generates KPI, risk, and decision summaries for weekly reviews.",
    impact: "Keeps stakeholders aligned with minimal manual effort.",
    defaultHref: "/app/reports",
    kpis: ["Report completion cadence", "Decision follow-through rate"],
    sprintTemplate: [
      "Compile weekly KPI and risk signals.",
      "Generate executive narrative and decision recommendations.",
      "Distribute report to workspace stakeholders.",
      "Track accepted actions and close-loop completion.",
    ],
  },
  {
    id: "integration-hub",
    title: "Integration Hub",
    category: "Ecosystem & Mobility",
    summary: "Connects productivity, ATS, and communication systems into one workflow layer.",
    impact: "Expands data coverage and reduces duplicate work.",
    defaultHref: "/app/command-center",
    kpis: ["Connected systems", "Sync freshness"],
    sprintTemplate: [
      "Prioritize integrations by impact and setup complexity.",
      "Configure ingestion and sync schedules.",
      "Validate field mapping and data quality.",
      "Monitor integration health and incident alerts.",
    ],
  },
  {
    id: "mobile-push-companion",
    title: "Mobile Companion + Push Alerts",
    category: "Ecosystem & Mobility",
    summary: "Provides mobile-first daily operating actions with high-priority alerting.",
    impact: "Improves responsiveness and execution continuity on the go.",
    defaultHref: "/app/help",
    kpis: ["Mobile action completion", "Alert response time"],
    sprintTemplate: [
      "Define mobile-critical actions and reminders.",
      "Enable push-priority tiers for SLA-sensitive events.",
      "Optimize layouts for phone and tablet breakpoints.",
      "Track mobile completion vs desktop completion.",
    ],
  },
  {
    id: "contextual-ai-copilot",
    title: "Contextual AI Copilot Everywhere",
    category: "AI Intelligence",
    summary: "Injects screen-aware AI guidance with one-click action execution across modules.",
    impact: "Creates continuous AI acceleration throughout the product.",
    defaultHref: "/app/ai-studio",
    kpis: ["Copilot action adoption", "Task-to-outcome cycle time"],
    sprintTemplate: [
      "Define contextual prompts per critical module.",
      "Attach one-click actions to AI recommendations.",
      "Measure prompt adoption and completion impact.",
      "Continuously refine prompts using usage telemetry.",
    ],
  },
  {
    id: "agentic-workflow-autotuner",
    title: "Agentic Workflow Autotuner",
    category: "AI Intelligence",
    summary: "Auto-adjusts execution workflows using live conversion and SLA telemetry.",
    impact: "Continuously improves throughput without manual process redesign.",
    defaultHref: "/app/command-center",
    kpis: ["Autotuned workflow count", "Execution lift vs baseline"],
    sprintTemplate: [
      "Enable autotuning on high-volume workflow lanes.",
      "Set guardrails for max daily workflow changes.",
      "Review tuned variants and lock high performers.",
      "Track lift and rollback noisy changes quickly.",
    ],
  },
  {
    id: "outreach-experiment-engine",
    title: "Outreach Experiment Engine",
    category: "Conversion Engine",
    summary: "Runs structured outreach tests across message variants and channel cadence.",
    impact: "Finds outreach patterns that maximize recruiter responses.",
    defaultHref: "/app/cover-letters",
    kpis: ["Experiment win rate", "Outreach conversion lift"],
    sprintTemplate: [
      "Define outreach hypotheses by role cluster.",
      "Launch controlled A/B sequences with equal traffic.",
      "Measure response and meeting conversion per variant.",
      "Promote winners into default outreach playbooks.",
    ],
  },
  {
    id: "recruiter-sentiment-intel",
    title: "Recruiter Sentiment Intelligence",
    category: "AI Intelligence",
    summary: "Scores inbound/outbound recruiter signals for urgency, fit, and engagement tone.",
    impact: "Prioritizes replies that have the highest conversion potential.",
    defaultHref: "/app/applications",
    kpis: ["Sentiment classification accuracy", "High-priority reply SLA"],
    sprintTemplate: [
      "Label current recruiter threads by sentiment band.",
      "Set escalation rules for high-intent opportunities.",
      "Tune response templates by sentiment archetype.",
      "Review downstream conversion impact weekly.",
    ],
  },
  {
    id: "interview-debrief-parser",
    title: "Interview Debrief Parser",
    category: "Conversion Engine",
    summary: "Converts interview notes and recordings into structured strengths and gaps.",
    impact: "Accelerates coaching loops between interview rounds.",
    defaultHref: "/app/interviews",
    kpis: ["Debrief coverage", "Gap closure by next round"],
    sprintTemplate: [
      "Capture debrief notes after every interview event.",
      "Extract recurring weakness themes and confidence gaps.",
      "Generate targeted improvement drills per theme.",
      "Validate improvement in next mock or live round.",
    ],
  },
  {
    id: "offer-package-comparator",
    title: "Offer Package Comparator",
    category: "Conversion Engine",
    summary: "Compares multi-offer packages across cash, equity, risk, and growth factors.",
    impact: "Improves final decision quality on competing opportunities.",
    defaultHref: "/app/salary-insights",
    kpis: ["Offer comparison completeness", "Decision confidence score"],
    sprintTemplate: [
      "Normalize compensation fields across incoming offers.",
      "Apply weighted decision criteria to each offer.",
      "Run downside-risk and upside-growth scenarios.",
      "Finalize ranked recommendations for decision review.",
    ],
  },
  {
    id: "kpi-anomaly-detector",
    title: "KPI Anomaly Detector",
    category: "Workflow Automation",
    summary: "Detects unusual KPI movement and flags likely root causes automatically.",
    impact: "Reduces time-to-response when conversion performance drifts.",
    defaultHref: "/app/reports",
    kpis: ["Anomaly detection precision", "Mean time to mitigation"],
    sprintTemplate: [
      "Define KPI baselines and allowable variance bands.",
      "Enable anomaly detection on core conversion metrics.",
      "Route anomaly alerts to owners with context.",
      "Track closure speed and recurrence rate.",
    ],
  },
  {
    id: "sla-breach-predictor",
    title: "SLA Breach Predictor",
    category: "Workflow Automation",
    summary: "Predicts upcoming follow-up SLA breaches before they occur.",
    impact: "Prevents pipeline decay by intervening early.",
    defaultHref: "/app/control-tower",
    kpis: ["Predicted breach recall", "Prevented breach count"],
    sprintTemplate: [
      "Score active records for breach likelihood.",
      "Create pre-breach intervention queue daily.",
      "Apply automated reminders and owner escalations.",
      "Measure prevented breaches vs projected breaches.",
    ],
  },
  {
    id: "role-cluster-optimizer",
    title: "Role Cluster Portfolio Optimizer",
    category: "AI Intelligence",
    summary: "Optimizes effort allocation across role clusters by expected offer yield.",
    impact: "Concentrates time on role segments with superior ROI.",
    defaultHref: "/app/roles",
    kpis: ["Cluster ROI score", "Effort allocation efficiency"],
    sprintTemplate: [
      "Group tracked roles into strategic clusters.",
      "Calculate conversion-adjusted expected value per cluster.",
      "Shift weekly effort toward top-yield clusters.",
      "Rebalance cluster mix from weekly outcomes.",
    ],
  },
  {
    id: "narrative-knowledge-graph",
    title: "Career Narrative Knowledge Graph",
    category: "AI Intelligence",
    summary: "Builds a linked graph of achievements, competencies, and story assets.",
    impact: "Improves retrieval and consistency of career messaging.",
    defaultHref: "/app/resumes",
    kpis: ["Narrative coverage index", "Story retrieval speed"],
    sprintTemplate: [
      "Map key achievements to competency nodes.",
      "Link stories to role families and modules.",
      "Identify weakly connected narrative areas.",
      "Fill missing evidence and strengthen graph coverage.",
    ],
  },
  {
    id: "applicant-benchmarking",
    title: "Applicant Benchmarking",
    category: "Conversion Engine",
    summary: "Benchmarks profile readiness against target-role market expectations.",
    impact: "Surfaces competitive gaps before late-stage rejection.",
    defaultHref: "/app/insights",
    kpis: ["Benchmark coverage", "Gap reduction vs benchmark"],
    sprintTemplate: [
      "Define benchmark profiles for key role families.",
      "Score profile against benchmark dimensions.",
      "Prioritize highest-penalty benchmark gaps.",
      "Track benchmark delta improvements weekly.",
    ],
  },
  {
    id: "talent-ops-workspace",
    title: "Talent Ops Workspace",
    category: "Collaboration & Governance",
    summary: "Dedicated multi-user workspace for candidate, coach, and hiring support teams.",
    impact: "Improves coordination and accountability across stakeholders.",
    defaultHref: "/app/workspaces",
    kpis: ["Workspace participation rate", "Decision turnaround time"],
    sprintTemplate: [
      "Create shared pods by operating objective.",
      "Assign owners and review cadences per pod.",
      "Capture decisions and blockers in workspace logs.",
      "Run weekly cross-pod operating review.",
    ],
  },
  {
    id: "coach-command-center",
    title: "Coach Command Center",
    category: "Collaboration & Governance",
    summary: "Provides advisor-focused oversight with interventions and coaching queues.",
    impact: "Improves coaching leverage across candidate execution cycles.",
    defaultHref: "/app/program-office",
    kpis: ["Coach intervention coverage", "Coaching-to-outcome conversion"],
    sprintTemplate: [
      "Configure coach-specific visibility dashboards.",
      "Identify candidates needing intervention this week.",
      "Issue targeted coaching actions with deadlines.",
      "Review intervention impact on conversion metrics.",
    ],
  },
  {
    id: "approval-escalation-bot",
    title: "Approval SLA Escalation Bot",
    category: "Collaboration & Governance",
    summary: "Escalates stalled approvals automatically based on SLA windows.",
    impact: "Keeps decision workflows moving without manual chasing.",
    defaultHref: "/app/program-office",
    kpis: ["Escalation resolution rate", "Approval SLA compliance"],
    sprintTemplate: [
      "Set SLA windows for each approval type.",
      "Enable automatic escalation routing on breaches.",
      "Audit false-positive escalations and tune rules.",
      "Publish approval latency trend by owner group.",
    ],
  },
  {
    id: "compliance-rule-builder",
    title: "Compliance Rule Builder",
    category: "Security & Compliance",
    summary: "No-code policy rule editor for retention, access, and event controls.",
    impact: "Speeds governance policy rollout without engineering bottlenecks.",
    defaultHref: "/app/security-center",
    kpis: ["Policy coverage", "Rule deployment lead time"],
    sprintTemplate: [
      "Define baseline policy templates by data class.",
      "Configure and test rules in staging mode.",
      "Promote approved rules to live enforcement.",
      "Track violations and policy false positives.",
    ],
  },
  {
    id: "data-residency-controls",
    title: "Data Residency Controls",
    category: "Security & Compliance",
    summary: "Controls where user data is stored and processed by region.",
    impact: "Improves enterprise trust for global and regulated users.",
    defaultHref: "/app/security-center",
    kpis: ["Residency policy adherence", "Region-compliant workload share"],
    sprintTemplate: [
      "Define region-specific residency requirements.",
      "Tag data domains with residency constraints.",
      "Validate routing and storage policy enforcement.",
      "Audit regional compliance exceptions weekly.",
    ],
  },
  {
    id: "pii-redaction-engine",
    title: "PII Redaction Engine",
    category: "Security & Compliance",
    summary: "Automatically redacts sensitive identifiers in logs, reports, and exports.",
    impact: "Reduces accidental exposure risk in operational workflows.",
    defaultHref: "/app/security-center",
    kpis: ["Redaction coverage", "Sensitive exposure incidents"],
    sprintTemplate: [
      "Define PII patterns and redaction classes.",
      "Scan existing logs and export pipelines for leaks.",
      "Enable redaction filters in reporting flows.",
      "Track redaction misses and patch pattern library.",
    ],
  },
  {
    id: "ai-safety-policy-guardrails",
    title: "AI Safety Policy Guardrails",
    category: "Security & Compliance",
    summary: "Enforces policy checks on prompts, outputs, and high-risk AI actions.",
    impact: "Prevents unsafe or non-compliant AI behavior in production.",
    defaultHref: "/app/security-center",
    kpis: ["Policy block accuracy", "Unsafe output incidents"],
    sprintTemplate: [
      "Define prohibited output and action classes.",
      "Enable guardrail checks for critical AI endpoints.",
      "Review blocked requests and tune thresholds.",
      "Report safety posture changes in weekly governance.",
    ],
  },
  {
    id: "prompt-experiment-lab",
    title: "Prompt Experiment Lab",
    category: "AI Intelligence",
    summary: "Tests prompt variants and evaluates response quality against target KPIs.",
    impact: "Improves AI output relevance and specificity over time.",
    defaultHref: "/app/ai-studio",
    kpis: ["Prompt win rate", "Output quality score"],
    sprintTemplate: [
      "Define prompt hypotheses for weak response areas.",
      "Run controlled prompt experiments on live-like tasks.",
      "Score outputs on specificity and actionability.",
      "Promote best prompts to production templates.",
    ],
  },
  {
    id: "model-routing-optimizer",
    title: "Model Routing + Cost Optimizer",
    category: "AI Intelligence",
    summary: "Routes requests to best-fit models based on task complexity and cost targets.",
    impact: "Improves response quality-to-cost efficiency.",
    defaultHref: "/app/ai-studio",
    kpis: ["Cost per successful task", "Model routing accuracy"],
    sprintTemplate: [
      "Classify requests by complexity and latency tolerance.",
      "Set routing policy for premium vs standard models.",
      "Track quality and cost outcomes by route.",
      "Tune routing thresholds for ROI improvements.",
    ],
  },
  {
    id: "rag-job-intel",
    title: "Retrieval-Augmented Job Intelligence",
    category: "AI Intelligence",
    summary: "Augments generation with indexed role, company, and historical execution context.",
    impact: "Reduces generic AI replies and improves contextual precision.",
    defaultHref: "/app/ai-studio",
    kpis: ["Context-grounded answer rate", "Unsupported claim rate"],
    sprintTemplate: [
      "Index high-value role and company knowledge sources.",
      "Attach retrieval context to copilot workflows.",
      "Audit groundedness and citation-quality metrics.",
      "Expand retrieval corpus based on gap analysis.",
    ],
  },
  {
    id: "browser-capture-extension",
    title: "Browser Capture Extension",
    category: "Ecosystem & Mobility",
    summary: "Captures jobs, contacts, and notes directly from browser pages into Climb.",
    impact: "Speeds top-of-funnel intake and context capture.",
    defaultHref: "/app/saved-jobs",
    kpis: ["Captured items per week", "Capture-to-application rate"],
    sprintTemplate: [
      "Define one-click capture schema for roles and contacts.",
      "Enable structured ingestion from major job boards.",
      "Review capture quality and deduplicate entries.",
      "Track downstream conversion from captured items.",
    ],
  },
  {
    id: "calendar-execution-planner",
    title: "Calendar Execution Planner",
    category: "Ecosystem & Mobility",
    summary: "Converts weekly targets into time-blocked calendar execution plans.",
    impact: "Improves consistency of daily operating rhythm.",
    defaultHref: "/app/goals",
    kpis: ["Scheduled execution blocks", "Plan adherence rate"],
    sprintTemplate: [
      "Translate weekly KPI targets into calendar blocks.",
      "Auto-schedule deep-work and follow-up windows.",
      "Track adherence and missed block patterns.",
      "Adjust next-week schedule using adherence data.",
    ],
  },
  {
    id: "collaboration-digest-integrations",
    title: "Slack/Teams Collaboration Digests",
    category: "Ecosystem & Mobility",
    summary: "Publishes periodic KPI and risk digests to collaboration channels.",
    impact: "Keeps stakeholders aligned without manual status reporting.",
    defaultHref: "/app/reports",
    kpis: ["Digest delivery reliability", "Digest engagement rate"],
    sprintTemplate: [
      "Configure digest templates for each stakeholder group.",
      "Set delivery schedules and severity-based alerts.",
      "Validate message clarity and action links.",
      "Measure engagement and iterate digest content.",
    ],
  },
  {
    id: "voice-notes-to-tasks",
    title: "Voice Notes to Tasks",
    category: "Ecosystem & Mobility",
    summary: "Turns voice memos into structured action tasks linked to modules.",
    impact: "Captures ideas fast and reduces action leakage.",
    defaultHref: "/app/command-center",
    kpis: ["Voice-to-task conversion", "Task completion from voice capture"],
    sprintTemplate: [
      "Define parsing template for spoken task extraction.",
      "Route parsed tasks to module-specific queues.",
      "Add confidence scoring for transcription quality.",
      "Review completion outcomes from voice-origin tasks.",
    ],
  },
  {
    id: "regional-market-intel",
    title: "Regional Market Intelligence",
    category: "Conversion Engine",
    summary: "Tracks role demand, compensation, and conversion dynamics by region.",
    impact: "Improves geo-specific targeting and offer strategy.",
    defaultHref: "/app/insights",
    kpis: ["Regional demand coverage", "Geo-targeting conversion lift"],
    sprintTemplate: [
      "Segment role pipeline by region and market type.",
      "Analyze conversion and compensation signals by region.",
      "Reweight targeting based on regional ROI.",
      "Review week-over-week regional performance shifts.",
    ],
  },
  {
    id: "credential-verification",
    title: "Skills Credential Verification",
    category: "Conversion Engine",
    summary: "Tracks validated credentials and maps them to target-role requirements.",
    impact: "Increases trust and qualification clarity in applications.",
    defaultHref: "/app/goals",
    kpis: ["Verified credential coverage", "Credential-linked response lift"],
    sprintTemplate: [
      "Inventory current certifications and credentials.",
      "Map credentials to role requirement clusters.",
      "Prioritize missing credentials by impact score.",
      "Track completion and signal lift after updates.",
    ],
  },
  {
    id: "portfolio-artifact-generator",
    title: "Portfolio Artifact Generator",
    category: "AI Intelligence",
    summary: "Generates role-relevant case studies and project narratives from existing work.",
    impact: "Creates stronger proof assets for high-signal applications.",
    defaultHref: "/app/documents",
    kpis: ["Generated artifact count", "Artifact usage in applications"],
    sprintTemplate: [
      "Select projects with strongest business outcomes.",
      "Generate concise case-study artifacts for each project.",
      "Map artifacts to role families and outreach flows.",
      "Track conversion impact of artifact-backed applications.",
    ],
  },
  {
    id: "negotiation-simulator",
    title: "Negotiation Scenario Simulator",
    category: "Conversion Engine",
    summary: "Simulates negotiation paths with likely employer responses and payoff ranges.",
    impact: "Improves preparedness and reduces negotiation anxiety.",
    defaultHref: "/app/salary-insights",
    kpis: ["Simulation completion rate", "Negotiation outcome uplift"],
    sprintTemplate: [
      "Define negotiation scenarios by offer type.",
      "Run scripted simulation with confidence scoring.",
      "Refine scripts for weak branches and objections.",
      "Finalize playbook for live negotiations.",
    ],
  },
  {
    id: "funnel-root-cause-analyzer",
    title: "Hiring Funnel Root Cause Analyzer",
    category: "Workflow Automation",
    summary: "Identifies dominant causes of drop-off by stage, role, and channel.",
    impact: "Improves precision of remediation plans.",
    defaultHref: "/app/insights",
    kpis: ["Root cause confidence", "Drop-off reduction rate"],
    sprintTemplate: [
      "Map funnel drop-offs by stage and segment.",
      "Prioritize root causes by expected impact.",
      "Launch targeted remediation experiments.",
      "Measure reduction in top drop-off drivers.",
    ],
  },
  {
    id: "autonomous-weekly-planner",
    title: "Autonomous Weekly Planning Agent",
    category: "Workflow Automation",
    summary: "Generates and updates weekly operating plans with KPI-aware task ladders.",
    impact: "Sustains high execution discipline with less manual planning overhead.",
    defaultHref: "/app/dashboard",
    kpis: ["Plan adherence", "Weekly KPI attainment"],
    sprintTemplate: [
      "Generate baseline weekly plan from live metrics.",
      "Auto-update plan when risk signals shift.",
      "Track daily completion and reprioritize tasks.",
      "Publish end-of-week execution retrospective.",
    ],
  },
  {
    id: "interview-panel-intel",
    title: "Interview Panel Intelligence",
    category: "AI Intelligence",
    summary: "Builds panel-specific preparation briefs from interviewer roles and likely question vectors.",
    impact: "Improves readiness for multi-interviewer loops.",
    defaultHref: "/app/interviews",
    kpis: ["Panel brief coverage", "Panel-round conversion rate"],
    sprintTemplate: [
      "Generate panel briefs for upcoming interviews.",
      "Map likely questions by interviewer function.",
      "Prepare evidence-backed response anchors per panelist.",
      "Review post-panel outcomes and refine briefing logic.",
    ],
  },
  {
    id: "offer-timeline-predictor",
    title: "Offer Timeline Predictor",
    category: "Conversion Engine",
    summary: "Estimates likely decision windows and offer timing by company and stage behavior.",
    impact: "Improves sequencing of applications and negotiations.",
    defaultHref: "/app/forecast",
    kpis: ["Timeline prediction accuracy", "Decision readiness timing"],
    sprintTemplate: [
      "Model decision timelines for top active opportunities.",
      "Flag opportunities with timeline slippage risk.",
      "Adjust follow-up cadence to predicted milestones.",
      "Measure prediction error and recalibrate weekly.",
    ],
  },
  {
    id: "referral-campaign-manager",
    title: "Referral Campaign Manager",
    category: "Collaboration & Governance",
    summary: "Runs multi-contact referral campaigns with sequencing, templates, and conversion tracking.",
    impact: "Scales warm-intro acquisition at predictable volume.",
    defaultHref: "/app/workspaces",
    kpis: ["Referral campaign yield", "Intro-to-application conversion"],
    sprintTemplate: [
      "Build campaign list across priority companies.",
      "Launch referral sequences with personalized asks.",
      "Track referral acceptance and intro completion.",
      "Optimize campaign messaging from conversion data.",
    ],
  },
  {
    id: "hiring-manager-outreach-sequencer",
    title: "Hiring Manager Outreach Sequencer",
    category: "Conversion Engine",
    summary: "Schedules role-aware outreach touchpoints to hiring managers and team leads.",
    impact: "Increases top-of-funnel engagement from decision-makers.",
    defaultHref: "/app/cover-letters",
    kpis: ["Manager outreach response rate", "Conversation-to-interview conversion"],
    sprintTemplate: [
      "Identify direct manager outreach opportunities.",
      "Generate sequenced messages with role-fit hooks.",
      "Track reply quality and escalation outcomes.",
      "Refresh sequence timing based on response latency.",
    ],
  },
  {
    id: "company-risk-radar",
    title: "Company Risk Radar",
    category: "AI Intelligence",
    summary: "Monitors macro and company-level risk signals that may affect hiring outcomes.",
    impact: "Reduces wasted effort on unstable opportunities.",
    defaultHref: "/app/horizons",
    kpis: ["Risk coverage for active pipeline", "Risk-informed reprioritization rate"],
    sprintTemplate: [
      "Attach risk scores to top pipeline companies.",
      "Set alerts for elevated hiring-risk signals.",
      "Reprioritize pipeline based on risk-adjusted potential.",
      "Audit missed risk signals and tune the radar model.",
    ],
  },
  {
    id: "jd-change-diff-alerts",
    title: "Job Description Change Diff Alerts",
    category: "Workflow Automation",
    summary: "Detects edits in tracked job descriptions and flags strategy-impacting changes.",
    impact: "Keeps application narratives aligned with latest requirements.",
    defaultHref: "/app/roles",
    kpis: ["Detected JD changes", "Updated applications after diff"],
    sprintTemplate: [
      "Enable change tracking for active role records.",
      "Classify diffs by strategic importance.",
      "Trigger resume and outreach refresh when needed.",
      "Measure response lift from fast diff handling.",
    ],
  },
  {
    id: "resume-lineage-tracker",
    title: "Resume Lineage Tracker",
    category: "Workflow Automation",
    summary: "Tracks ancestry and performance of resume variants across roles and outcomes.",
    impact: "Improves variant governance and reusability.",
    defaultHref: "/app/resumes",
    kpis: ["Variant lineage completeness", "Winning lineage reuse rate"],
    sprintTemplate: [
      "Map existing variants into lineage chains.",
      "Attach conversion outcomes to each branch.",
      "Promote high-performing lineages to templates.",
      "Retire low-performing branches and document learnings.",
    ],
  },
  {
    id: "artifact-impact-scoring",
    title: "Artifact Impact Scoring",
    category: "Conversion Engine",
    summary: "Scores resumes, cover letters, and case artifacts by contribution to pipeline movement.",
    impact: "Focuses optimization on assets that drive outcomes.",
    defaultHref: "/app/insights",
    kpis: ["Asset impact score coverage", "High-impact asset utilization"],
    sprintTemplate: [
      "Score all active artifacts against conversion signals.",
      "Rank assets by observed impact contribution.",
      "Upgrade top-impact assets with targeted improvements.",
      "Track impact score changes after updates.",
    ],
  },
  {
    id: "recruiter-crm-autopilot",
    title: "Recruiter CRM Autopilot",
    category: "Workflow Automation",
    summary: "Automates recruiter relationship upkeep with reminders and context-aware follow-ups.",
    impact: "Sustains recruiter engagement without manual tracking overhead.",
    defaultHref: "/app/workspaces",
    kpis: ["Autopilot touch completion", "Recruiter re-engagement rate"],
    sprintTemplate: [
      "Enable cadence rules for recruiter touchpoints.",
      "Auto-generate context-aware follow-up drafts.",
      "Escalate dormant high-value recruiter threads.",
      "Measure engagement lift from CRM automation.",
    ],
  },
  {
    id: "follow-up-tone-optimizer",
    title: "Follow-up Tone Optimizer",
    category: "AI Intelligence",
    summary: "Optimizes follow-up tone and framing by target persona and stage context.",
    impact: "Improves response quality while preserving professionalism.",
    defaultHref: "/app/cover-letters",
    kpis: ["Tone score trend", "Follow-up response uplift"],
    sprintTemplate: [
      "Classify follow-up templates by tone archetype.",
      "Match tone to persona and stage conditions.",
      "Test tone variants across active opportunities.",
      "Promote best-performing tone models globally.",
    ],
  },
  {
    id: "smart-application-batching",
    title: "Smart Application Batching",
    category: "Workflow Automation",
    summary: "Bundles role applications into high-focus production batches by similarity and urgency.",
    impact: "Increases output quality and execution speed.",
    defaultHref: "/app/applications",
    kpis: ["Batch completion rate", "Batch-level conversion quality"],
    sprintTemplate: [
      "Group pipeline roles into strategic batch clusters.",
      "Set batch goals for quality and submission volume.",
      "Run focused production sessions per batch.",
      "Compare batch outcomes and rebalance strategy.",
    ],
  },
  {
    id: "pipeline-capacity-planner",
    title: "Pipeline Capacity Planner",
    category: "Workflow Automation",
    summary: "Calculates sustainable weekly throughput based on available time and quality targets.",
    impact: "Prevents overload and quality drop-offs.",
    defaultHref: "/app/forecast",
    kpis: ["Capacity utilization", "Quality stability under load"],
    sprintTemplate: [
      "Estimate weekly capacity by task category.",
      "Set role and application quotas within capacity.",
      "Track overload signals and quality decay.",
      "Adjust quotas dynamically from utilization trends.",
    ],
  },
  {
    id: "weekly-retrospective-agent",
    title: "Weekly Retrospective Agent",
    category: "Collaboration & Governance",
    summary: "Generates structured weekly retrospectives with wins, misses, and corrective actions.",
    impact: "Improves learning velocity across execution cycles.",
    defaultHref: "/app/reports",
    kpis: ["Retro completion cadence", "Action closure from retros"],
    sprintTemplate: [
      "Generate end-of-week performance retrospective.",
      "Capture top wins, misses, and root causes.",
      "Assign corrective actions with owners and due dates.",
      "Review closure rate at next governance meeting.",
    ],
  },
  {
    id: "decision-journal-assistant",
    title: "Decision Journal Assistant",
    category: "Collaboration & Governance",
    summary: "Logs strategic decisions with context, assumptions, and later outcome checks.",
    impact: "Improves decision quality through feedback loops.",
    defaultHref: "/app/program-office",
    kpis: ["Decision log completeness", "Assumption validation rate"],
    sprintTemplate: [
      "Capture high-impact decisions in a structured journal.",
      "Record assumptions and expected outcomes per decision.",
      "Schedule outcome review checkpoints.",
      "Refine future decisions from historical outcomes.",
    ],
  },
  {
    id: "governance-kpi-scorecards",
    title: "Governance KPI Scorecards",
    category: "Collaboration & Governance",
    summary: "Creates operating scorecards across velocity, quality, risk, and forecast dimensions.",
    impact: "Enables consistent executive-level governance reviews.",
    defaultHref: "/app/program-office",
    kpis: ["Scorecard freshness", "KPI review completion rate"],
    sprintTemplate: [
      "Define KPI set and target bands by module.",
      "Generate weekly scorecards with owner mapping.",
      "Flag red-zone KPIs for intervention planning.",
      "Track scorecard-driven decision outcomes.",
    ],
  },
  {
    id: "incident-postmortem-generator",
    title: "Operational Postmortem Generator",
    category: "Security & Compliance",
    summary: "Creates postmortem reports for major execution incidents and SLA failures.",
    impact: "Improves resilience by formalizing incident learning.",
    defaultHref: "/app/security-center",
    kpis: ["Postmortem completion time", "Repeat incident reduction"],
    sprintTemplate: [
      "Trigger postmortem on severe SLA or risk events.",
      "Capture timeline, root cause, and impact.",
      "Define preventive actions with ownership.",
      "Track completion of postmortem action items.",
    ],
  },
  {
    id: "ai-budget-governor",
    title: "AI Budget Governor",
    category: "Security & Compliance",
    summary: "Controls AI consumption budgets per module, user tier, and workload class.",
    impact: "Prevents runaway AI costs while protecting critical flows.",
    defaultHref: "/app/security-center",
    kpis: ["Budget adherence rate", "Critical flow continuity"],
    sprintTemplate: [
      "Set AI budget envelopes by module and tier.",
      "Prioritize mission-critical workloads under constraints.",
      "Apply throttling and fallback policies by severity.",
      "Review spend vs value and adjust budgets weekly.",
    ],
  },
  {
    id: "prompt-safety-simulator",
    title: "Prompt Safety Simulator",
    category: "Security & Compliance",
    summary: "Stress-tests prompts against policy boundaries before production deployment.",
    impact: "Reduces unsafe prompt behavior in live traffic.",
    defaultHref: "/app/ai-studio",
    kpis: ["Safety test pass rate", "Pre-production issue detection"],
    sprintTemplate: [
      "Select prompt sets for adversarial testing.",
      "Run policy-boundary simulations on each set.",
      "Patch unsafe patterns and retest quickly.",
      "Promote only passing prompt versions to production.",
    ],
  },
  {
    id: "compliance-evidence-vault",
    title: "Compliance Evidence Vault",
    category: "Security & Compliance",
    summary: "Stores auditable evidence for policy controls, reviews, and remediation actions.",
    impact: "Accelerates compliance readiness for enterprise audits.",
    defaultHref: "/app/security-center",
    kpis: ["Evidence completeness", "Audit preparation lead time"],
    sprintTemplate: [
      "Define evidence artifacts for each control domain.",
      "Automate evidence capture from operational systems.",
      "Review evidence freshness and gap alerts.",
      "Prepare quarterly audit-ready evidence bundles.",
    ],
  },
  {
    id: "secure-share-links",
    title: "Secure Share Links",
    category: "Security & Compliance",
    summary: "Creates time-limited secure links for sharing reports, assets, and snapshots.",
    impact: "Improves collaboration while minimizing exposure risk.",
    defaultHref: "/app/reports",
    kpis: ["Secure link adoption", "Expired-link access incidents"],
    sprintTemplate: [
      "Enable expiring links for report sharing workflows.",
      "Set role and domain restrictions on shared links.",
      "Audit access logs for unusual behavior.",
      "Rotate and revoke links on risk triggers.",
    ],
  },
  {
    id: "mobile-quick-capture",
    title: "Mobile Quick Capture",
    category: "Ecosystem & Mobility",
    summary: "Provides instant capture actions for jobs, notes, and follow-ups on mobile.",
    impact: "Reduces opportunity loss when away from desktop workflows.",
    defaultHref: "/app/help",
    kpis: ["Mobile capture volume", "Capture follow-through rate"],
    sprintTemplate: [
      "Configure one-tap mobile capture actions.",
      "Route captures into module-specific inbox queues.",
      "Set reminders for unprocessed mobile captures.",
      "Track conversion from captures to completed actions.",
    ],
  },
  {
    id: "offline-mission-mode",
    title: "Offline Mission Mode",
    category: "Ecosystem & Mobility",
    summary: "Allows task execution and data capture with sync-on-reconnect behavior.",
    impact: "Maintains execution continuity in low-connectivity environments.",
    defaultHref: "/app/command-center",
    kpis: ["Offline session completion", "Sync success rate"],
    sprintTemplate: [
      "Define offline-critical tasks and data models.",
      "Enable local queueing for mission actions.",
      "Validate sync conflict handling on reconnect.",
      "Monitor offline-to-online recovery reliability.",
    ],
  },
  {
    id: "tablet-ops-board",
    title: "Tablet Operations Board",
    category: "Ecosystem & Mobility",
    summary: "Optimized tablet board for reviewing pipeline, risks, and priorities in one view.",
    impact: "Improves portability for daily and weekly operating reviews.",
    defaultHref: "/app/dashboard",
    kpis: ["Tablet session usage", "Tablet board task completion"],
    sprintTemplate: [
      "Define board widgets for tablet workflows.",
      "Optimize layout and touch interactions for iPad.",
      "Validate KPI readability across tablet orientations.",
      "Track board usage and action conversion rates.",
    ],
  },
  {
    id: "ats-submission-checkpoint",
    title: "ATS Submission Checkpoint",
    category: "Conversion Engine",
    summary: "Final gate that validates content, format, and requirement fit before submission.",
    impact: "Reduces preventable submission errors.",
    defaultHref: "/app/applications",
    kpis: ["Pre-submit issue catch rate", "Submission quality score"],
    sprintTemplate: [
      "Define mandatory pre-submit checks by role type.",
      "Run checkpoint scans on outgoing applications.",
      "Block and fix high-severity submission issues.",
      "Track error-rate reduction after checkpoint rollout.",
    ],
  },
  {
    id: "interview-question-radar",
    title: "Interview Question Radar",
    category: "AI Intelligence",
    summary: "Forecasts likely interview questions from role requirements and company context.",
    impact: "Improves specificity of prep and answer readiness.",
    defaultHref: "/app/interviews",
    kpis: ["Radar hit rate", "Prepared-answer coverage"],
    sprintTemplate: [
      "Generate question radar for active interview tracks.",
      "Map anticipated questions to STAR stories.",
      "Score preparedness by question cluster.",
      "Refine radar from post-interview debrief data.",
    ],
  },
  {
    id: "practice-gap-heatmap",
    title: "Practice Gap Heatmap",
    category: "Conversion Engine",
    summary: "Visualizes interview and communication weaknesses by topic and confidence level.",
    impact: "Targets practice time where it yields maximum improvement.",
    defaultHref: "/app/interviews",
    kpis: ["Gap heatmap coverage", "Weak-area score lift"],
    sprintTemplate: [
      "Generate topic-level gap heatmap from session history.",
      "Prioritize top red-zone topics for drills.",
      "Run focused practice loops for selected topics.",
      "Measure score improvement and update heatmap weekly.",
    ],
  },
  {
    id: "executive-brief-narrator",
    title: "Executive Brief Narrator",
    category: "Collaboration & Governance",
    summary: "Converts KPI and risk data into concise executive narratives for leadership updates.",
    impact: "Improves communication quality in weekly operating reviews.",
    defaultHref: "/app/reports",
    kpis: ["Brief generation cadence", "Stakeholder clarity score"],
    sprintTemplate: [
      "Generate weekly narrative from KPI deltas.",
      "Highlight critical risks and proposed interventions.",
      "Attach action owners and decision deadlines.",
      "Capture feedback and improve narrative structure.",
    ],
  },
  {
    id: "multi-candidate-program-view",
    title: "Multi-Candidate Program View",
    category: "Collaboration & Governance",
    summary: "Program-level view for teams managing multiple candidate pipelines simultaneously.",
    impact: "Enables portfolio-level resource and risk planning.",
    defaultHref: "/app/workspaces",
    kpis: ["Portfolio visibility coverage", "Cross-candidate SLA compliance"],
    sprintTemplate: [
      "Aggregate candidate pipelines into a unified view.",
      "Define portfolio-level risk and capacity metrics.",
      "Reallocate support based on portfolio priorities.",
      "Review portfolio outcomes in weekly governance cycle.",
    ],
  },
  {
    id: "partner-portal",
    title: "Partner Collaboration Portal",
    category: "Ecosystem & Mobility",
    summary: "External partner portal for advisors, recruiters, and mentors with scoped access.",
    impact: "Expands collaboration reach while preserving control boundaries.",
    defaultHref: "/app/workspaces",
    kpis: ["Partner participation rate", "Partner-driven opportunity lift"],
    sprintTemplate: [
      "Define partner roles and scope boundaries.",
      "Provision partner portal access with policy controls.",
      "Track partner contributions and response quality.",
      "Optimize partner workflows from participation metrics.",
    ],
  },
  {
    id: "cross-functional-war-room",
    title: "Cross-Functional War Room",
    category: "Collaboration & Governance",
    summary: "Shared mission room for urgent, high-impact pipeline and interview situations.",
    impact: "Accelerates coordinated response during critical conversion windows.",
    defaultHref: "/app/command-center",
    kpis: ["War room resolution time", "Critical-situation win rate"],
    sprintTemplate: [
      "Define trigger conditions for war room activation.",
      "Assign rapid-response roles and decision rights.",
      "Run synchronized action loops during critical windows.",
      "Capture outcomes and fold learnings into playbooks.",
    ],
  },
  {
    id: "ai-readiness-signal-scoring",
    title: "AI Readiness Signal Scoring",
    category: "AI Intelligence",
    summary: "Continuously scores readiness for AI-led execution across every module.",
    impact: "Identifies weak execution zones before performance drops.",
    defaultHref: "/app/ai-studio",
    kpis: ["Readiness score trend", "Readiness-to-outcome correlation"],
    sprintTemplate: [
      "Compute readiness baseline across active modules.",
      "Flag low-readiness zones with remediation owners.",
      "Execute corrective actions for lowest-scoring areas.",
      "Re-score and compare lift after interventions.",
    ],
  },
  {
    id: "role-intake-assistant",
    title: "Role Intake Assistant",
    category: "Workflow Automation",
    summary: "Guides structured role intake with quality checks before prioritization.",
    impact: "Improves consistency and speed of role onboarding.",
    defaultHref: "/app/roles/new",
    kpis: ["Role intake completeness", "Time-to-prioritization"],
    sprintTemplate: [
      "Enable guided intake for all new role entries.",
      "Apply mandatory requirement and risk checks.",
      "Queue accepted roles into ranking workflow.",
      "Audit rejected or incomplete intake submissions.",
    ],
  },
  {
    id: "auto-fit-gap-remediator",
    title: "Auto Fit-Gap Remediator",
    category: "AI Intelligence",
    summary: "Automatically proposes and sequences fixes for detected role-fit gaps.",
    impact: "Shrinks time from gap detection to actionable remediation.",
    defaultHref: "/app/roles",
    kpis: ["Gap remediation completion rate", "Fit score uplift velocity"],
    sprintTemplate: [
      "Detect high-impact fit gaps in active targets.",
      "Generate prioritized remediation tasks per gap.",
      "Apply fixes to resumes and narratives.",
      "Measure fit lift and close resolved gaps.",
    ],
  },
  {
    id: "outreach-reply-classifier",
    title: "Outreach Reply Classifier",
    category: "AI Intelligence",
    summary: "Classifies replies by intent and urgency to prioritize next actions.",
    impact: "Reduces missed opportunities in high-velocity outreach cycles.",
    defaultHref: "/app/applications",
    kpis: ["Classification precision", "High-intent response SLA"],
    sprintTemplate: [
      "Classify all new outreach replies by intent.",
      "Auto-prioritize high-urgency response queues.",
      "Tune classifier with false-positive/negative review.",
      "Track conversion impact from prioritized handling.",
    ],
  },
  {
    id: "follow-up-outcome-forecaster",
    title: "Follow-up Outcome Forecaster",
    category: "Conversion Engine",
    summary: "Predicts follow-up effectiveness by stage, timing, and message profile.",
    impact: "Optimizes follow-up sequences for higher response yield.",
    defaultHref: "/app/forecast",
    kpis: ["Forecast accuracy for follow-ups", "Follow-up response lift"],
    sprintTemplate: [
      "Forecast outcome probability for pending follow-ups.",
      "Adjust timing and copy based on forecast bands.",
      "Run revised follow-up schedule on target cohort.",
      "Compare forecasted vs actual response outcomes.",
    ],
  },
  {
    id: "interview-style-calibrator",
    title: "Interview Style Calibrator",
    category: "Conversion Engine",
    summary: "Calibrates answer style, pacing, and depth against interviewer expectations.",
    impact: "Improves answer resonance across varied interview styles.",
    defaultHref: "/app/interviews",
    kpis: ["Style match score", "Answer quality consistency"],
    sprintTemplate: [
      "Profile target interview style archetypes.",
      "Calibrate mock responses to each archetype.",
      "Score pacing and depth against style targets.",
      "Refine weak styles through focused drills.",
    ],
  },
  {
    id: "keyword-saturation-analyzer",
    title: "Keyword Saturation Analyzer",
    category: "AI Intelligence",
    summary: "Detects under- and over-saturation of critical role keywords in assets.",
    impact: "Balances ATS relevance with natural readability.",
    defaultHref: "/app/resumes",
    kpis: ["Keyword balance score", "ATS readability tradeoff index"],
    sprintTemplate: [
      "Scan resume and cover assets for keyword saturation.",
      "Identify missing and overused keyword clusters.",
      "Adjust language to optimal keyword density.",
      "Re-test ATS and readability score tradeoffs.",
    ],
  },
  {
    id: "role-portfolio-diversifier",
    title: "Role Portfolio Diversifier",
    category: "Conversion Engine",
    summary: "Diversifies role targeting to balance upside, fit, and risk exposure.",
    impact: "Reduces dependency on narrow role clusters.",
    defaultHref: "/app/horizons",
    kpis: ["Portfolio diversity score", "Risk-adjusted opportunity mix"],
    sprintTemplate: [
      "Measure current concentration across role clusters.",
      "Define target mix by risk and conversion potential.",
      "Add diversified high-fit opportunities weekly.",
      "Track conversion changes after diversification.",
    ],
  },
  {
    id: "application-deadline-guardian",
    title: "Application Deadline Guardian",
    category: "Workflow Automation",
    summary: "Monitors deadlines and enforces pre-deadline submission playbooks.",
    impact: "Prevents deadline misses on high-value opportunities.",
    defaultHref: "/app/applications",
    kpis: ["Deadline compliance", "Late submission incidents"],
    sprintTemplate: [
      "Attach deadlines to all active opportunities.",
      "Trigger pre-deadline milestone reminders.",
      "Escalate at-risk submissions to priority queue.",
      "Review missed deadlines and root causes weekly.",
    ],
  },
  {
    id: "rejection-pattern-miner",
    title: "Rejection Pattern Miner",
    category: "Conversion Engine",
    summary: "Finds recurring rejection patterns across stage, role, and message features.",
    impact: "Turns rejection data into targeted improvement loops.",
    defaultHref: "/app/insights",
    kpis: ["Pattern confidence score", "Rejection recurrence reduction"],
    sprintTemplate: [
      "Mine rejection events by stage and role cluster.",
      "Extract top recurring failure signatures.",
      "Launch corrective experiments for key patterns.",
      "Track recurrence reduction after interventions.",
    ],
  },
  {
    id: "cover-letter-quality-linter",
    title: "Cover Letter Quality Linter",
    category: "AI Intelligence",
    summary: "Runs rule-based and AI checks for clarity, specificity, and alignment.",
    impact: "Improves letter quality before submission.",
    defaultHref: "/app/cover-letters",
    kpis: ["Lint pass rate", "Specificity score uplift"],
    sprintTemplate: [
      "Define quality lint rules by letter stage.",
      "Run linter on all outgoing cover letters.",
      "Resolve flagged issues prior to send.",
      "Track response lift from linted submissions.",
    ],
  },
  {
    id: "resume-proof-point-expander",
    title: "Resume Proof-Point Expander",
    category: "AI Intelligence",
    summary: "Expands weak claims into evidence-backed proof points and outcomes.",
    impact: "Raises trust and impact clarity in resume content.",
    defaultHref: "/app/resumes",
    kpis: ["Proof-point density", "Evidence-backed bullet ratio"],
    sprintTemplate: [
      "Identify low-evidence statements in active resumes.",
      "Generate proof-point expansions for each statement.",
      "Validate claims against known experience artifacts.",
      "Publish updated variants and track conversion impact.",
    ],
  },
  {
    id: "goals-outcome-simulator",
    title: "Goals Outcome Simulator",
    category: "Conversion Engine",
    summary: "Simulates likely outcomes for different goal-setting strategies.",
    impact: "Improves target realism and execution confidence.",
    defaultHref: "/app/goals",
    kpis: ["Goal simulation adoption", "Goal attainment accuracy"],
    sprintTemplate: [
      "Model outcomes for current goal configurations.",
      "Compare aggressive vs balanced goal strategies.",
      "Adopt scenario with best risk-adjusted outcomes.",
      "Track actual vs simulated attainment weekly.",
    ],
  },
  {
    id: "mentorship-matching-engine",
    title: "Mentorship Matching Engine",
    category: "Collaboration & Governance",
    summary: "Matches candidates with mentors by role goals, skill gaps, and working style.",
    impact: "Improves coaching relevance and effectiveness.",
    defaultHref: "/app/workspaces",
    kpis: ["Mentor match quality", "Mentorship conversion impact"],
    sprintTemplate: [
      "Profile candidate and mentor compatibility vectors.",
      "Run matching for top mentorship needs.",
      "Launch mentorship engagement plans.",
      "Review mentorship outcomes and refine matching.",
    ],
  },
  {
    id: "advisor-feedback-loop",
    title: "Advisor Feedback Loop",
    category: "Collaboration & Governance",
    summary: "Structured loop for collecting, prioritizing, and applying advisor feedback.",
    impact: "Transforms feedback into measurable execution improvements.",
    defaultHref: "/app/program-office",
    kpis: ["Feedback closure rate", "Feedback-to-outcome lift"],
    sprintTemplate: [
      "Capture advisor feedback into structured queue.",
      "Prioritize feedback by expected impact.",
      "Apply top feedback changes to active workflows.",
      "Measure outcome lift from applied feedback.",
    ],
  },
  {
    id: "team-capacity-balancer",
    title: "Team Capacity Balancer",
    category: "Workflow Automation",
    summary: "Balances work allocation across collaborators based on load and priority.",
    impact: "Improves throughput without overloading key contributors.",
    defaultHref: "/app/workspaces",
    kpis: ["Load balance index", "Throughput per collaborator"],
    sprintTemplate: [
      "Map current task load across contributors.",
      "Rebalance assignments by priority and capacity.",
      "Track overload signals and rebalance dynamically.",
      "Review throughput gains from balanced allocation.",
    ],
  },
  {
    id: "sprint-burndown-tracker",
    title: "Sprint Burndown Tracker",
    category: "Workflow Automation",
    summary: "Tracks daily burn progress for feature and execution sprints.",
    impact: "Improves predictability of sprint completion.",
    defaultHref: "/app/enterprise-lab",
    kpis: ["Burndown adherence", "Sprint completion reliability"],
    sprintTemplate: [
      "Initialize burndown baselines for active sprints.",
      "Update completion burn daily.",
      "Flag slippage trends and recovery actions.",
      "Run sprint-end variance analysis.",
    ],
  },
  {
    id: "action-priority-engine",
    title: "Action Priority Engine",
    category: "Workflow Automation",
    summary: "Ranks tasks by impact, urgency, dependency, and effort.",
    impact: "Ensures teams work on highest-value actions first.",
    defaultHref: "/app/command-center",
    kpis: ["Priority alignment rate", "High-impact task completion"],
    sprintTemplate: [
      "Score all tasks with priority engine criteria.",
      "Reorder queues by composite impact score.",
      "Execute top-priority tasks within SLA windows.",
      "Review score calibration against outcomes.",
    ],
  },
  {
    id: "cross-module-dependency-mapper",
    title: "Cross-Module Dependency Mapper",
    category: "Workflow Automation",
    summary: "Maps inter-module dependencies and blocks risky sequencing conflicts.",
    impact: "Reduces execution delays caused by hidden dependencies.",
    defaultHref: "/app/horizons",
    kpis: ["Dependency mapping coverage", "Dependency-caused delay reduction"],
    sprintTemplate: [
      "Identify dependencies across active module actions.",
      "Map critical paths and sequencing risks.",
      "Adjust plans to resolve dependency blockers.",
      "Track delay reduction after dependency mapping.",
    ],
  },
  {
    id: "audit-retention-manager",
    title: "Audit Retention Manager",
    category: "Security & Compliance",
    summary: "Enforces retention windows and archival policies for audit data.",
    impact: "Improves compliance posture and storage governance.",
    defaultHref: "/app/security-center",
    kpis: ["Retention compliance rate", "Policy violation count"],
    sprintTemplate: [
      "Define retention windows by audit data class.",
      "Apply archival and purge schedules automatically.",
      "Verify retention policy compliance with sampling.",
      "Remediate retention exceptions and document evidence.",
    ],
  },
  {
    id: "access-review-automation",
    title: "Access Review Automation",
    category: "Security & Compliance",
    summary: "Automates periodic access reviews and stale-permission cleanup.",
    impact: "Reduces privilege creep and access risk.",
    defaultHref: "/app/security-center",
    kpis: ["Access review completion", "Stale access revocation rate"],
    sprintTemplate: [
      "Generate review lists for all privileged roles.",
      "Collect owner attestations for active permissions.",
      "Revoke stale or unnecessary access grants.",
      "Track review SLA and revocation outcomes.",
    ],
  },
  {
    id: "data-minimization-advisor",
    title: "Data Minimization Advisor",
    category: "Security & Compliance",
    summary: "Advises on reducing stored sensitive data to minimum necessary scope.",
    impact: "Lowers privacy and compliance risk surface.",
    defaultHref: "/app/security-center",
    kpis: ["Sensitive data footprint", "Minimization action completion"],
    sprintTemplate: [
      "Inventory sensitive fields across active datasets.",
      "Recommend minimization actions by risk level.",
      "Apply reduction and masking changes safely.",
      "Measure risk-footprint decrease post-remediation.",
    ],
  },
  {
    id: "pii-access-anomaly-monitor",
    title: "PII Access Anomaly Monitor",
    category: "Security & Compliance",
    summary: "Detects unusual access patterns to sensitive personal data.",
    impact: "Improves early detection of potential data misuse.",
    defaultHref: "/app/security-center",
    kpis: ["Anomaly detection recall", "Time to incident triage"],
    sprintTemplate: [
      "Baseline normal PII access patterns.",
      "Trigger anomaly alerts for suspicious behavior.",
      "Triage and classify anomalies by severity.",
      "Tune detection thresholds from incident outcomes.",
    ],
  },
  {
    id: "export-integrity-verifier",
    title: "Export Integrity Verifier",
    category: "Security & Compliance",
    summary: "Validates data export completeness, checksum integrity, and policy compliance.",
    impact: "Improves trust in governance export workflows.",
    defaultHref: "/app/security-center",
    kpis: ["Export integrity pass rate", "Export defect count"],
    sprintTemplate: [
      "Define integrity checks for export pipelines.",
      "Run checksum and completeness verification jobs.",
      "Flag and remediate failed export artifacts.",
      "Publish weekly export integrity report.",
    ],
  },
  {
    id: "integration-health-ops",
    title: "Integration Health Ops",
    category: "Ecosystem & Mobility",
    summary: "Operations cockpit for monitoring integration uptime, latency, and error rates.",
    impact: "Improves reliability of connected data workflows.",
    defaultHref: "/app/command-center",
    kpis: ["Integration uptime", "Mean time to integration recovery"],
    sprintTemplate: [
      "Set health SLIs for all active integrations.",
      "Monitor latency and failure spikes in real time.",
      "Escalate and remediate degraded connectors.",
      "Track uptime improvement after remediation.",
    ],
  },
  {
    id: "sync-conflict-resolver",
    title: "Sync Conflict Resolver",
    category: "Ecosystem & Mobility",
    summary: "Detects and resolves data sync conflicts across connected systems.",
    impact: "Prevents stale or inconsistent state across modules.",
    defaultHref: "/app/workspaces",
    kpis: ["Conflict resolution time", "Conflict recurrence rate"],
    sprintTemplate: [
      "Surface active sync conflicts with severity levels.",
      "Apply automated resolution where confidence is high.",
      "Route ambiguous conflicts to owner review queues.",
      "Analyze recurrence and strengthen sync rules.",
    ],
  },
  {
    id: "mobile-focus-mode",
    title: "Mobile Focus Mode",
    category: "Ecosystem & Mobility",
    summary: "Distraction-minimized mobile workflow mode for critical daily actions.",
    impact: "Improves completion rate on high-priority mobile tasks.",
    defaultHref: "/app/help",
    kpis: ["Focus session completion", "High-priority mobile task rate"],
    sprintTemplate: [
      "Define focus-mode task bundles by day.",
      "Enable interruption-limiting UI for focus sessions.",
      "Track completion vs non-focus baseline.",
      "Adjust focus bundles from completion outcomes.",
    ],
  },
  {
    id: "smart-notification-throttler",
    title: "Smart Notification Throttler",
    category: "Ecosystem & Mobility",
    summary: "Intelligently throttles low-value alerts while escalating critical signals.",
    impact: "Reduces alert fatigue and improves response to priority events.",
    defaultHref: "/app/settings/preferences",
    kpis: ["Alert fatigue index", "Critical alert response rate"],
    sprintTemplate: [
      "Classify notifications by business criticality.",
      "Throttle non-critical alerts by context and load.",
      "Escalate urgent signals through priority channels.",
      "Measure response improvement and fatigue reduction.",
    ],
  },
  {
    id: "recruiting-events-playbook",
    title: "Recruiting Events Playbook",
    category: "Conversion Engine",
    summary: "Playbook engine for webinars, career fairs, and networking event conversion.",
    impact: "Turns event participation into structured opportunity generation.",
    defaultHref: "/app/help",
    kpis: ["Event-to-opportunity conversion", "Event follow-up completion"],
    sprintTemplate: [
      "Create event-specific outreach and follow-up templates.",
      "Capture contacts and actions during each event.",
      "Execute post-event sequence within 48 hours.",
      "Track conversion from event contacts to interviews.",
    ],
  },
  {
    id: "strategic-opportunity-map",
    title: "Strategic Opportunity Map",
    category: "AI Intelligence",
    summary: "Visual map of opportunities by impact, fit, competition, and timing.",
    impact: "Improves strategic targeting and opportunity sequencing.",
    defaultHref: "/app/horizons",
    kpis: ["Mapped opportunity coverage", "Top-tier opportunity conversion"],
    sprintTemplate: [
      "Map active opportunities on strategic matrix.",
      "Prioritize high-impact, high-fit opportunities.",
      "Sequence execution based on timing and competition.",
      "Review map movement and retarget weekly.",
    ],
  },
]

export const ENTERPRISE_FEATURE_CATALOG = FEATURE_CATALOG
export const ENTERPRISE_FEATURE_COUNT = FEATURE_CATALOG.length

export const ENTERPRISE_FEATURE_CATEGORY_ORDER: EnterpriseFeatureCategory[] = [
  "AI Intelligence",
  "Conversion Engine",
  "Workflow Automation",
  "Collaboration & Governance",
  "Security & Compliance",
  "Ecosystem & Mobility",
]

export function getEnterpriseFeatureById(featureId: string) {
  return ENTERPRISE_FEATURE_CATALOG.find((feature) => feature.id === featureId) || null
}

export function isEnterpriseFeatureId(featureId: string): boolean {
  return ENTERPRISE_FEATURE_CATALOG.some((feature) => feature.id === featureId)
}

export function buildDefaultRollout(featureId: string): EnterpriseFeatureRollout {
  const feature = getEnterpriseFeatureById(featureId)
  return {
    featureId,
    status: "live",
    priority: 85,
    owner: feature?.category === "Security & Compliance" ? "Security Lead" : "AI Program Owner",
    notes: "Activated in enterprise suite rollout.",
    lastRunAt: null,
    updatedAt: null,
  }
}

export function buildDefaultFeatureSuite(): EnterpriseFeatureWithRollout[] {
  return ENTERPRISE_FEATURE_CATALOG.map((feature) => ({
    ...feature,
    ...buildDefaultRollout(feature.id),
  }))
}

export function summarizeFeatureSuite(features: EnterpriseFeatureWithRollout[]) {
  const total = features.length
  const live = features.filter((item) => item.status === "live").length
  const inProgress = features.filter((item) => item.status === "in_progress").length
  const planned = features.filter((item) => item.status === "planned").length
  const backlog = features.filter((item) => item.status === "backlog").length
  const avgPriority =
    features.length > 0
      ? Math.round(
          features.reduce((sum, item) => sum + Math.max(0, Math.min(100, Number(item.priority) || 0)), 0) /
            features.length
        )
      : 0

  return {
    total,
    live,
    inProgress,
    planned,
    backlog,
    avgPriority,
    completionPct: total > 0 ? Math.round((live / total) * 100) : 0,
  }
}
